import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import  {inter}  from "./fonts/font";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <title>Job Spring</title>
        <link rel="shortcut icon" href="/flask.svg" type="image/x-icon" />
        <meta title="JobSpring - AI Interviews & Tailored Resumes for Smarter Job Search" />
        <meta name="description" content="JobSpring enhances your job search with AI-driven interview preparation and tailored resumes. Boost your chances of success with smart career tools powered by AI!" />
        <meta name="keywords" content="AI job interview, AI interview preparation, tailored resumes, AI resume builder, smart job search, automated job applications, AI career assistant, resume optimization, interview coaching, job application automation, AI-powered hiring, resume tailoring, career growth tools, job search automation, AI recruitment" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body
        className={`${inter} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
